version: '3.8'

services:
  php:
    container_name: meu-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    container_name: meu-nginx
    build:
      context: .
    image: nginx:latest
    ports:
      - "8989:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - php
    restart: unless-stopped

  mysql:
    container_name: meu-mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network: